### ISSUE TITLE
please grade my homework @adwasser

### ISSUE THREAD

**Issue by lwooliev** [lwooliev/-astr-119-hw-1#1]

**Comment by adwasser** [comment]
@lwooliev, for future reference you can submit your HW by mentioning me (i.e., typing `@adwasser` in the body of an issue.  Writing it in the title doesn't raise up the issue for me.

**Comment by lwooliev** [comment]
My bad, I'll make sure to do that on this weeks hw.

**Comment by adwasser** [comment]
@lwooliev , could you mark this issue as closed?  Thanks!
